services:
    sandbox_init_cms.menu.navbar_menu_builder:
        class: Sandbox\InitCmsBundle\Component\Menu\NavbarFrontendMenuBuilder
        scope: request
        arguments: [ '@knp_menu.factory', '@security.context', '@service_container' ]

    # Create the left main menu and right main menu for the frontend
    sandbox_init_cms.menu.frontend_main_menu_left:
        class: Knp\Menu\MenuItem
        factory_service: sandbox_init_cms.menu.navbar_menu_builder
        factory_method: createMainMenu
        arguments: [ '@request', path: "The main menu", "nav nav-tabs nav-main" ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    sandbox_init_cms.menu.frontend_main_menu_login:
        class: Knp\Menu\MenuItem
        factory_service: sandbox_init_cms.menu.navbar_menu_builder
        factory_method: createCMSMenu
        arguments: [ '@request', %networking_init_cms.page.languages% ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: loginMenu }

    sandbox_init_cms.menu.frontend_main_menu_language:
        class: Knp\Menu\MenuItem
        factory_service: sandbox_init_cms.menu.navbar_menu_builder
        factory_method: createFrontendLangMenu
        arguments: [ '@request', %networking_init_cms.page.languages%, "nav nav-pills pull-right" ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: langMenu }

    sandbox_init_cms.menu.frontend_top_menu_template:
        class: %mopa_bootstrap.navbar.generic%
        scope: request
        arguments:
            - { pageMenu: @sandbox_init_cms.menu.frontend_main_menu_left=, langMenu: @sandbox_init_cms.menu.frontend_main_menu_language=}
            - {}
            - { logo: "bundles/sandboxinitcms/img/sailing_icon_grey.png", title: "Demo Sailing Club", titleRoute: "networking_init_cms_home", fixedTop: false, isFluid: false, template: SandboxInitCmsBundle:Navbar:navbar.html.twig }
        tags:
            - { name: mopa_bootstrap.navbar, alias: cmsNavbar }

    # Create the side menu for the frontend
    sandbox_init_cms.menu.frontend_sub_menu:
        class: Knp\Menu\MenuItem
        factory_service: sandbox_init_cms.menu.navbar_menu_builder
        factory_method: createNavbarsSubnavMenu
        arguments: [ '@request', "The main menu", 'nav nav-pills']
        scope: request
        tags:
            - { name: knp_menu.menu, alias: subMenu }


    sandbox_init_cms.menu.frontend_sub_menu_template:
        class: %mopa_bootstrap.navbar.generic%
        arguments:
            # first argument: a named array of menues:
            - { menu: @sandbox_init_cms.menu.frontend_sub_menu= }
            - {}
            # third argument: a named array of options
            - { template: SandboxInitCmsBundle:Navbar:subnavbar.html.twig }
        tags:
            # The alias is used to retrieve the navbar in templates
            - { name: mopa_bootstrap.navbar, alias: subNavbar }

    sandbox_init_cms.menu.frontend_footer_menu:
        class: Knp\Menu\MenuItem
        factory_service: sandbox_init_cms.menu.navbar_menu_builder
        factory_method: createFooterMenu
        arguments: [ @request, 'Footer Menu', 'nav nav-pills']
        scope: request
        tags:
            - { name: knp_menu.menu, alias: footerMenu }

    sandbox_init_cms.menu.frontend_footer_menu_template:
        class: %mopa_bootstrap.navbar.generic%
        arguments:
            # first argument: a named array of menues:
            - { menu: @sandbox_init_cms.menu.frontend_footer_menu= }
            - {}
            # third argument: a named array of options
            - { template: SandboxInitCmsBundle:Navbar:footernavbar.html.twig }
        tags:
            # The alias is used to retrieve the navbar in templates
            - { name: mopa_bootstrap.navbar, alias: footerNavbar }